### ISSUE TITLE
Improve handling of custom locations in astral

### ISSUE THREAD

**Issue by basil96** [basil96/civilite#1]
The current **astral.py** module we use here is a local copy from the official astral package, with custom locations added to the **_LOCATION_INFO** string.  See if it's possible to add a custom location from client side so we would eliminate **astral.py** from this project and just use the official package via pip so that future updates to astral go smoothly.

**Comment by scliddle** [comment]
I clearly made a mistake @basil96 I meant to push a branch with my changes for review, but they ended up on master. I'm not sure how I did that. I'll try to fix it.

**Comment by scliddle** [comment]
It seems like I fixed the glitch, now I think its a regular pull request.

**Comment by scliddle** [comment]
Whenever that merge completes properly, please close this!

**Comment by basil96** [comment]
Done.  I had added the "trying squash merge" comment thinking it would perform the merge, but that's not it.  Then I went back and did the actual merge, and it worked!
I believe at this point you can see all the detailed progress commits in your local repo, while the master has them all squashed into one with all the commit messages simply auto-collected into one message on master.
The other issue, I believe, is that your work in #3 needs to be synched with current master to get all the changes from #2 before you can push...
