### ISSUE TITLE
insights/dependencies point to incorrect astral

### ISSUE THREAD

**Issue by scliddle** [basil96/civilite#13]
I wonder how we fix this. 

our [insights/dependencies ](https://github.com/basil96/civilite/network/dependencies) points to

https://github.com/peplin/astral

instead of 

https://github.com/sffjunkie/astral

when I pip installed, it picked the right one. I wonder if this is something we can do in requirements.txt or if we need to report it to GitHub.

**Comment by basil96** [comment]
Pip installs the correct one because there's only one such name in PyPi.  The other got incorrectly picked up by GH.

**Comment by basil96** [comment]
GitHub should know that for a Python project it should be looking at the PyPi index first, then spider through matches to find a possible link to a repo here.

**Comment by basil96** [comment]
astral's homepage on PyPi.org links to the correct repo here on GitHub...

**Comment by scliddle** [comment]
I agree the index should be checked first. maybe contact GitHub?

**Comment by basil96** [comment]
I'll contact support.  If no answer, I'll try the forum.

**Comment by basil96** [comment]
GitHub fixed it today.
